# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

#steps:
#- script: dotnet build TNZAPI.NET/TNZAPI.NET.csproj -c $(buildConfiguration)
#  displayName: 'dotnet build TNZAPI.NET/TNZAPI.NET.csproj $(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'pack'
#    packagesToPack: '**/*.csproj;!**/*.Tests.csproj;!**/*.Samples.csproj'
#    versioningScheme: 'off'
#  displayName: 'Create package'

#- task: NuGetCommand@2
#  inputs:
#    command: 'push'
#    #packagesToPush: '$(Build.ArtifactStagingDirectory)/*.symbols.nupkg'
#    #packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg'
#    packagesToPush: '$(Agent.ReleaseDirectory)/**/*.nupkg;!$(Agent.ReleaseDirectory)/**/*.symbols.nupkg'
#    nuGetFeedType: 'external'
#    publishFeedCredentials: 'TNZAPI.NET.Nuget'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.csproj;!**/*.Samples.csproj'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: '**/*.csproj;!**/*.Samples.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    #packagesToPush: '$(Build.ArtifactStagingDirectory)/*.symbols.nupkg'
    #packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg'
    packagesToPush: '$(Agent.ReleaseDirectory)/**/*.nupkg;!$(Agent.ReleaseDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'TNZAPI.NET.Nuget'