# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 9.x
    performMultiLevelLookup: true
    
- script: dotnet build TNZAPI.NET/*.csproj -c $(buildConfiguration)
  displayName: 'dotnet build TNZAPI.NET/*.csproj $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packDirectory: "$(Build.ArtifactStagingDirectory)/packages"
    packagesToPack: 'TNZAPI.NET/*.csproj;'
    versioningScheme: 'off'
  displayName: 'Create package'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/*.*nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'TNZAPI.NET.Nuget'
